Name: policy-settings-basic-n900
Summary: Precompiled basic MeeGo policy settings for the N900
Version: 0.1.2
Release: 1
Group: System/Resource Policy
License: GPLv2
Sources:
    - "%{name}-%{version}.tar.gz"
URL: https://github.com/nemomobile/policy-settings-basic/
Description: Precompiled basic MeeGo policy settings for the N900.

Requires:
    - ohm >= 1.1.16
    - ohm-plugins-misc
    - ohm-plugin-resolver
    - ohm-plugin-ruleengine
    - ohm-plugin-videoep
    - ohm-plugin-fmradio
    - ohm-plugin-dspep
    - ohm-plugins-dbus
    - ohm-plugin-telephony
    - ohm-plugin-media
    - ohm-plugin-accessories
    - pulseaudio-policy-enforcement
PkgBR:
    - libdres-utils
    - swi-prolog
    - swi-prolog-library
    - libprolog
    - prolog-resourcepolicy-extensions
Provides:
    - policy-settings
Configure: autogen
Builder: none
BuildArch: noarch
SubPackages:
    - Name: text
      Summary: Basic MeeGo policy settings sources for the N900
      Group: System/Resource Policy
      Description: Basic MeeGo policy settings sources for the N900.
      AutoDepend: false
      Requires:
          - swi-prolog-library
          - ohm >= 1.1.16
          - ohm-plugins-misc
          - ohm-plugin-resolver
          - ohm-plugin-ruleengine
          - pulseaudio-policy-enforcement
      Provides:
          - policy-settings

